//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using Microsoft.AspNetCore.Components;
using MyFeedRss.Domain.FeedRss;

namespace MyFeedRss.Components.FeedsRss;

public partial class FeedRssDetail
{
    [Parameter]
    public IFeedRss FeedRssInfo {  get; set; }
}
